/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gogitek.clientapp.view.thuoc;

import com.gogitek.clientapp.model.Thuoc;
import com.gogitek.clientapp.service.ThuocService;
import com.gogitek.clientapp.service.ThuocServiceImpl;
import com.gogitek.clientapp.view.Home;

import java.util.List;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 * @author bmtnt
 */
public class JThuoc extends javax.swing.JFrame {

    private final ThuocService thuocService;
    private List<Thuoc> list;

    /**
     * Creates new form Thuoc
     */
    public JThuoc() {
        initComponents();
        tableThuoc.setEnabled(false);
        initData();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        thuocService = new ThuocServiceImpl();
    }

    public void initData() {
        try {
            list = (List<Thuoc>) thuocService.findListThuocByKey(null).getResult();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        DefaultTableModel model = (DefaultTableModel) tableThuoc.getModel();
        for (Thuoc value : list) {
            Object[] rowData = new Object[6];
            rowData[0] = value.getId();
            rowData[1] = value.getMaThuoc();
            rowData[2] = value.getTenThuoc();
            rowData[3] = value.getDangThuoc();
            rowData[4] = value.getGiaThuoc();
            rowData[5] = value.getCongDungId();
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableThuoc = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        inputName = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        tableThuoc.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "ID", "Mã Thuốc", "Tên Thuốc", "Dạng Thuốc", "Giá Thuốc", "Công Dụng"
                }
        ));
        tableThuoc.setEnabled(false);
        tableThuoc.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                tableThuocComponentAdded(evt);
            }
        });
        tableThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableThuocMouseClicked(evt);
            }

            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableThuocMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableThuoc);

        jLabel1.setText("QUẢN LÝ THUỐC");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        inputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNameActionPerformed(evt);
            }
        });

        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnRefresh.setText("Làm mới");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnThem)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnRefresh)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnSearch)))
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(282, 282, 282)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnThem)
                                        .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSearch)
                                        .addComponent(btnRefresh))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNameActionPerformed

    private void tableThuocComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tableThuocComponentAdded
        // TODO add your handling code here:        
    }//GEN-LAST:event_tableThuocComponentAdded

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        new JThemThuoc().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnThemActionPerformed

    private void tableThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableThuocMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tableThuoc.getModel();
        Vector<Object> v = (Vector<Object>) model.getDataVector().elementAt(tableThuoc.convertRowIndexToModel(tableThuoc.rowAtPoint(evt.getPoint())));
        Thuoc thuoc = new Thuoc((Long) v.get(0), (String) v.get(1), (String) v.get(4), (Double) v.get(5), (String) v.get(3), (Long) v.get(6));
        (new JEditThuoc(thuoc)).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_tableThuocMouseClicked

    private void tableThuocMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableThuocMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableThuocMousePressed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:        
        inputName.setText("");
        DefaultTableModel model = (DefaultTableModel) tableThuoc.getModel();
        model.setRowCount(0);
        List<Thuoc> list1 = null;
        try {
            list1 = (List<Thuoc>) thuocService.findListThuocByKey(null).getResult();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        for (Thuoc value : list1) {
            Object[] rowData = new Object[6];
            rowData[0] = value.getId();
            rowData[1] = value.getMaThuoc();
            rowData[2] = value.getTenThuoc();
            rowData[3] = value.getDangThuoc();
            rowData[4] = value.getGiaThuoc();
            rowData[5] = value.getCongDungId();
            model.addRow(rowData);
        }
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        // TODO add your handling code here:            
        DefaultTableModel model = (DefaultTableModel) tableThuoc.getModel();
        model.setRowCount(0);
        List<Thuoc> list1;


        String key = inputName.getText();
        list1 = (List<Thuoc>) thuocService.findListThuocByKey(key).getResult();

        for (Thuoc value : list1) {
            Object[] rowData = new Object[6];
            rowData[0] = value.getId();
            rowData[1] = value.getMaThuoc();
            rowData[2] = value.getTenThuoc();
            rowData[3] = value.getDangThuoc();
            rowData[4] = value.getGiaThuoc();
            rowData[5] = value.getCongDungId();
            model.addRow(rowData);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        new Home().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Thuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Thuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Thuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Thuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JThuoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnThem;
    private javax.swing.JTextField inputName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableThuoc;
    // End of variables declaration//GEN-END:variables
}
